### PR TITLE
Replaced random.shuffle with pyudorandom

### PR DESCRIPTION
**Pull request by mewwts**
Hi @CamDavidsonPilon, 

I have been meaning to do this PR for a while now, but instead of including lots of utility code in your repo, I placed it in https://github.com/mewwts/pyudorandom. 

For larger lists, `random.shuffle` can be very slow, and simple tests show that pyudorandom can be up to twice as fast. 

I understand that introducing dependencies is something you would rather not, but I think this can be a meaningful change.

Keep in mind that this change will not guarantee randomness, but rather will pick elements non-successively from the list. I think that is what is needed here.

If there's any modifications to this PR you would like to have made, please do not hesitate.

### CODE REVIEW

**Comment by mewwts** [comment]
@CamDavidsonPilon, not certain why `test_uniform` would fail. Does my code touch any code used in that?

**Comment by CamDavidsonPilon** [comment]
Neat! There's a third shuffle here: https://github.com/CamDavidsonPilon/tdigest/pull/11/files#diff-a2984f32c7c535cc1813f346efcbec8fL141, can that be replaced too?

**Comment by CamDavidsonPilon** [comment]
That error looked like a statistical fluke, rerunning tests now.

**Comment by mewwts** [comment]
Cool @CamDavidsonPilon, I'll replace the other shuffle in a sec!

**Comment by CamDavidsonPilon** [comment]
lgtm!

**Comment by mewwts** [comment]
:+1:

**Comment by CamDavidsonPilon** [comment]
Forgot to do this: https://pypi.python.org/pypi/tdigest

**Comment by mewwts** [comment]
Cool, thanks!

**Pull request merged**
