### PR TITLE
Fix typo in private method name

### PR DESCRIPTION
**Pull request by vivienm**
I think I've found a small typo in a method name :)

### CODE REVIEW

**Comment by vivienm** [comment]
There is a failed test, but I don't think it's related to the change?

**Comment by IntegersOfK** [comment]
Yeah it seems to fail, but only sometimes. I opened an issue so we can track it #39.

**Comment by vivienm** [comment]
Thanks!

**Comment by CamDavidsonPilon** [comment]
Thanks @vivienm!

**Pull request merged**
